# Data Cleaning 01

In [41]:
import pandas as pd

In [42]:
customers=pd.read_csv("olist_customers_dataset.csv")

In [43]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

### columns:

customer_id =  
key to the orders dataset. Each order has a unique customer_id.

customer_unique_id  =  
unique identifier of a customer.

customer_zip_code_prefix =  
first five digits of customer zip code

customer_city  =  
customer city name

customer_state  =  
customer state


#### new column
state_name =  
state name using customer_state

In [44]:
# the types of each columns
customers.dtypes

customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

In [45]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 11.0 MB

In [46]:
#To make a new colum to state name
customers["customer_state"].unique()

<ArrowStringArray>
['SP', 'SC', 'MG', 'PR', 'RJ', 'RS', 'PA', 'GO', 'ES', 'BA', 'MA', 'MS', 'CE',
 'DF', 'RN', 'PE', 'MT', 'AM', 'AP', 'AL', 'RO', 'PB', 'TO', 'PI', 'AC', 'SE',
 'RR']
Length: 27, dtype: str

In [47]:
# collect the names of each state :
state_names = {
    'AC': 'Acre',
    'AL': 'Alagoas',
    'AP': 'Amapa',
    'AM': 'Amazonas',
    'BA': 'Bahia',
    'CE': 'Ceara',
    'ES': 'Espirito Santo',
    'GO': 'Goias',
    'MA': 'Maranhao',
    'MT': 'Mato Grosso',
    'MS': 'Mato Grosso do Sul',
    'MG': 'Minas Gerais',
    'PA': 'Para',
    'PB': 'Paraiba',
    'PR': 'Parana',
    'PE': 'Pernambuco',
    'PI': 'Piaui',
    'RJ': 'Rio de Janeiro',
    'RN': 'Rio Grande do Norte',
    'RS': 'Rio Grande do Sul',
    'RO': 'Rondonia',
    'RR': 'Roraima',
    'SC': 'Santa Catarina',
    'SP': 'Sao Paulo',
    'SE': 'Sergipe',
    'TO': 'Tocantins',
    'DF': 'Federal District'
}

In [48]:
#new column for name state :
customers['state_name'] = customers['customer_state'].map(state_names)

In [49]:
#filter same zip code and international 
# code=geolocation[geolocation["state_name"]=="international"]["geolocation_zip_code_prefix"]
# # filter same zip code but not international
# code2=geolocation[geolocation["state_name"]!="international"]["geolocation_zip_code_prefix"]
# code= code[code.isin(code2) == False]


# customers.loc[customers["customer_zip_code_prefix"].isin(code),["customer_city","customer_state", "state_name"]]="international"

In [50]:
print((customers["state_name"] == "international").sum())

0

In [51]:
# check the dublicate:
customers.duplicated().sum()

np.int64(0)

In [52]:
# check if there is null values :
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
state_name                  0
dtype: int64

In [53]:
customers.to_csv("olist_customers_dataset_cleaned.csv", index=False)

## sellers dataset

In [54]:
# read the data 
sellers=pd.read_csv("olist_sellers_dataset.csv")

In [55]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

### columns : 
seller_id =   
seller unique identifier

seller_zip_code_prefix  =  
first 5 digits of seller zip code

seller_city  = 
seller city name

seller_state =  
seller state

##### new column:
seller_state_name = 
the name of each state

In [56]:
sellers.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 230.3 KB

In [57]:
sellers.dtypes

seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

In [58]:
# To add new column (seller_state_name)
sellers["seller_state"].unique()

<ArrowStringArray>
['SP', 'RJ', 'PE', 'PR', 'GO', 'SC', 'BA', 'DF', 'RS', 'MG', 'RN', 'MT', 'CE',
 'PB', 'AC', 'ES', 'RO', 'PI', 'MS', 'SE', 'MA', 'AM', 'PA']
Length: 23, dtype: str

In [59]:
sellers["seller_state_name"]= sellers['seller_state'].map(state_names)

In [60]:
# check duplicated :
sellers.duplicated().sum()

np.int64(0)

In [61]:
# check if there any null value:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
seller_state_name         0
dtype: int64

In [62]:
# save it :
sellers.to_csv("olist_sellers_dataset_cleaned.csv", index=False)

## olist_geolocation_dataset.csv
## geolocation dataset

In [63]:
# read the data
geolocation=pd.read_csv("olist_geolocation_dataset.csv")

In [64]:
geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

### columns : 
geolocation_zip_code_prefix   =  
first 5 digits of zip code

geolocation_lat = 
latitude

geolocation_lng =  
longitude

geolocation_city  =  
city name


geolocation_state  =  
state

##### new column
state_name = 
the name of each state in brazil

In [65]:
# Explore data :
geolocation.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 50.1 MB

In [66]:
customers.describe(include="str")

,customer_id,customer_unique_id,customer_city,customer_state,state_name
count,99441,99441,99441,99441,99441
unique,99441,96096,4119,27,27
top,06b8999e2fba1a1fbc88172c00ba8bc7,8d50f5eadf50201ccdcedfb9e2ac8455,sao paulo,SP,Sao Paulo
freq,1,17,15540,41746,41746

In [67]:
# explore more data
geolocation["geolocation_city"].unique()

<ArrowStringArray>
[            'sao paulo',             'são paulo', 'sao bernardo do campo',
               'jundiaí',       'taboão da serra',              'sãopaulo',
                    'sp',            'sa£o paulo',   'sao jose dos campos',
                'osasco',
 ...
       'ipiranga do sul',          'vila langaro',               'ciriaco',
      'floriano peixoto',              'erebango',                'ibiaçá',
  'santa cecilia do sul',               'ciríaco',               'estação',
          'vila lângaro']
Length: 8011, dtype: str

In [68]:
geolocation["geolocation_state"].unique()

<ArrowStringArray>
['SP', 'RN', 'AC', 'RJ', 'ES', 'MG', 'BA', 'SE', 'PE', 'AL', 'PB', 'CE', 'PI',
 'MA', 'PA', 'AP', 'AM', 'RR', 'DF', 'GO', 'RO', 'TO', 'MT', 'MS', 'RS', 'PR',
 'SC']
Length: 27, dtype: str

In [69]:
# add new column : name of states:
geolocation["state_name"] = geolocation["geolocation_state"].map(state_names)

In [70]:
geolocation["state_name"].value_counts()

state_name
Sao Paulo              404268
Minas Gerais           126336
Rio de Janeiro         121169
Rio Grande do Sul       61851
Parana                  57859
Santa Catarina          38328
Bahia                   36045
Goias                   20139
Espirito Santo          16748
Pernambuco              16432
Federal District        12986
Mato Grosso             12031
Ceara                   11674
Para                    10853
Mato Grosso do Sul      10431
Maranhao                 7853
Paraiba                  5538
Rio Grande do Norte      5041
Piaui                    4549
Alagoas                  4183
Tocantins                3576
Sergipe                  3563
Rondonia                 3478
Amazonas                 2432
Acre                     1301
Amapa                     853
Roraima                   646
Name: count, dtype: int64

In [71]:
# change the wrong city and state if the location not in Brazil :

In [72]:
# take the maximum and minimum for lat and lng for Brazil :
brazil = (geolocation["geolocation_lat"].between(-33.75, 5.27)& geolocation["geolocation_lng"].between(-73.99, -34.79))

#replace brazil city or state name with international
geolocation.loc[brazil == False, ["geolocation_city","geolocation_state", "state_name"]]="international"

In [73]:
#updated state name column:
geolocation["state_name"].value_counts()

state_name
Sao Paulo              404267
Minas Gerais           126334
Rio de Janeiro         121164
Rio Grande do Sul       61847
Parana                  57856
Santa Catarina          38328
Bahia                   36041
Goias                   20139
Espirito Santo          16746
Pernambuco              16421
Federal District        12986
Mato Grosso             12030
Ceara                   11674
Para                    10846
Mato Grosso do Sul      10431
Maranhao                 7853
Paraiba                  5537
Rio Grande do Norte      5041
Piaui                    4549
Alagoas                  4182
Tocantins                3576
Sergipe                  3563
Rondonia                 3478
Amazonas                 2432
Acre                     1301
Amapa                     853
Roraima                   646
international              42
Name: count, dtype: int64

In [74]:
# check dublicated : 
geolocation.duplicated().sum()

np.int64(261831)

In [75]:
geolocation["geolocation_zip_code_prefix"].duplicated().sum()

np.int64(981148)

In [76]:
# so, we drop the dublicated 
geolocation=geolocation.drop_duplicates()

In [77]:
# check again : 
geolocation.duplicated().sum()

np.int64(0)

In [78]:
# check null value: 
geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
state_name                     0
dtype: int64

In [79]:
# If there ia a customers not in Brazil :
# ckeck the longitude , latitude from geolocation dataset , then change the wrong state , then replace it in this data 
code = geolocation[geolocation["state_name"] == "international"]["geolocation_zip_code_prefix"]
customers.loc[customers["customer_zip_code_prefix"].isin(code), ["customer_city", "customer_state", "state_name"]] = "international"

In [80]:
# check :
customers["state_name"].value_counts()

state_name
Sao Paulo              41746
Rio de Janeiro         12847
Minas Gerais           11619
Rio Grande do Sul       5455
Parana                  5041
Santa Catarina          3637
Bahia                   3376
Federal District        2140
Espirito Santo          2032
Goias                   2020
Pernambuco              1652
Ceara                   1336
Para                     969
Mato Grosso              907
Maranhao                 747
Mato Grosso do Sul       715
Paraiba                  536
Piaui                    495
Rio Grande do Norte      485
Alagoas                  412
Sergipe                  350
Tocantins                280
Rondonia                 253
Amazonas                 148
Acre                      81
Amapa                     68
international             48
Roraima                   46
Name: count, dtype: int64

In [81]:
customers.to_csv("olist_geolocation_dataset_cleaned.csv", index = False)